// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocumentationExpert.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocumentationExpert.Vsix.6e205403-eb2f-4a65-8b91-7c48cd762c94";
        public const string Name = "Documentation Expert";
        public const string Description = @"An extension to help with xml documentation (method, class summaries & file headers)";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "DEVLKFSCCM01";
        public const string Tags = "";
    }
}
