// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocumentationExpert.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DocumentationExpertVsixString = "fde40217-8d50-4253-89ad-c990f956e4bd";
        public static Guid DocumentationExpertVsix = new Guid(DocumentationExpertVsixString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FileHeaderGroup = 0x0001;
        public const int SetFileHeader = 0x0100;
        public const int ApplyDocumentationFix = 0x0110;
    }
}